### ISSUE TITLE
Function of Final Code and LLCNN Evaluation

### ISSUE THREAD

**Issue by denys2109** [aayush9753/Image-Enhancement-and-Super-Resolution#1]
Hello, i wanna ask about final code in your repositories. So what the function for that final code? and why you not include LLCNN evaluation in your evaluation_test? Thankyou before :)

**Comment by yusdiansya** [comment]
Hallo, i wanna ask about Image Enhancement and Super Resolution. I have problem with SRGAN, on your jurnal the title is ESRGAN and it is about ESRGAN after that on your code, the name of file code is SRGAN. So the question is Super Resolution using what SRGAN or ESRGAN because the journal discusses ESRGAN while the file name code is SRGAN? thank you

**Comment by aayush9753** [comment]
@yusdiansya I am using SRGAN not ESRGAN.  Check the paper -
https://github.com/aayush9753/Image-Enhancement-and-Super-Resolution/blob/main/Research%20Papers/SRGAN.pdf

**Comment by aayush9753** [comment]
@denys2109 Final is another model to pass the srgan generated images. The Final is llcnn kinda model to simply make the generated image more smooth.
